import React, { useEffect, useState, useRef } from 'react';
import Nav from '../Nav2/Nav2';
import axios from "axios";
import User from '../User/User';
import html2pdf from 'html2pdf.js';
import '../UserDetails/users.css';

const URL = "http://localhost:8070/users";

const fetchHandler = async () => {
  return await axios.get(URL).then((res) => res.data);
}

function Users() {
  const [users, setUsers] = useState([]);
  const [searchQuery, setSearchQuery] = useState("");
  const [noResult, setNoResult] = useState(false);
  const userTableRef = useRef();

  useEffect(() => {
    fetchHandler().then((data) => {
      console.log("Fetched users data:", data.users);
      setUsers(data.users);
    });
  }, []);

  const downloadUsersPDF = () => {
    // Create a clean version of the user table for PDF
    const userReport = document.createElement('div');
    userReport.innerHTML = `
      <div style="padding: 20px; font-family: Arial, sans-serif;">
        <h2 style="text-align: center;">User Details Report</h2>
        <p style="text-align: center;">Generated on ${new Date().toLocaleString()}</p>
        <hr style="margin: 20px 0;"/>
        
        <table style="width: 100%; border-collapse: collapse;">
          <thead>
            <tr style="background-color: #f2f2f2;">
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Name</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Email</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Age</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Address</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Department</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Employee ID</th>
              <th style="padding: 8px; border: 1px solid #ddd; text-align: left;">Role</th>
            </tr>
          </thead>
          <tbody>
            ${users.map(user => `
              <tr>
                <td style="padding: 8px; border: 1px solid #ddd;">${user.name || 'N/A'}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${user.gmail || 'N/A'}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${user.age || 'N/A'}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${user.address || 'N/A'}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${user.department || 'N/A'}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${user.employeeId || 'N/A'}</td>
                <td style="padding: 8px; border: 1px solid #ddd;">${user.role || 'customer'}</td>
              </tr>
            `).join('')}
          </tbody>
        </table>
        
        <div style="margin-top: 30px;">
          <p><strong>Total Users:</strong> ${users.length}</p>
          <p><strong>Report Generated By:</strong> ${localStorage.getItem('userName') || 'Administrator'}</p>
        </div>
      </div>
    `;

    const opt = {
      margin: 10,
      filename: `user_details_report_${new Date().toISOString().split('T')[0]}.pdf`,
      image: { type: 'jpeg', quality: 0.98 },
      html2canvas: { scale: 2 },
      jsPDF: { unit: 'mm', format: 'a4', orientation: 'landscape' }
    };

    try {
      html2pdf().set(opt).from(userReport).save();
    } catch (error) {
      console.error("Error generating PDF:", error);
      alert("Failed to generate PDF. Please try again.");
    }
  };

  const handleSearch = () => {
    fetchHandler().then((data) => {
      const filteredUsers = data.users.filter((user) =>
        Object.values(user).some((field) =>
          field.toString().toLowerCase().includes(searchQuery.toLowerCase())
        )
      );
      setUsers(filteredUsers);
      setNoResult(filteredUsers.length === 0);
    });
  };

  const handleSendReport = () => {
    const phoneNumber = "+94718784455";
    const message = `User Details Report`;
    const WhatsAppUrl = `https://web.whatsapp.com/send?phone=${phoneNumber}&text=${encodeURIComponent(message)}`;
    window.open(WhatsAppUrl, "_blank");
  }

  return (
    <div className="abc-container">
      <Nav />
      
      <div className="user-details-container">
        <h1>User Details</h1>
        
        <div className="search-section">
          <input 
            type="text" 
            name="search"
            placeholder="Search users by name, email, or address..." 
            value={searchQuery} 
            onChange={(e) => setSearchQuery(e.target.value)}
          />
          <button onClick={handleSearch}>
            <i className="fas fa-search"></i> Search
          </button>
        </div>

        {noResult && <p className="no-result">No users found</p>}
      </div>


      <div className="users-grid" ref={userTableRef}>
        <User users={users} setUsers={setUsers} />
      </div>
      <div className="buttons" >
        
        <button className="btn btn-primary1" onClick={downloadUsersPDF}>
          <i className="fas fa-download"></i> Download PDF
        </button>
        <button className="btn btn-primary" onClick={handleSendReport}>
          <i className="fab fa-whatsapp"></i> Send WhatsApp Message
        </button>
       
      </div>

      <footer className="footer">
        <div className="footer-content">
          <div className="footer-section">
            <div className="footer-logo">
              <span className="logo-icon">MEAL</span>
              <span>mate</span>
            </div>
            <p className="footer-about">
              Your trusted partner for delicious and convenient hostel dining. We make every meal special with quality ingredients and excellent service.
            </p>
            <div className="social-links">
              <a href="#"><i className="fab fa-facebook-f"></i></a>
              <a href="#"><i className="fab fa-twitter"></i></a>
              <a href="#"><i className="fab fa-instagram"></i></a>
              <a href="#"><i className="fab fa-linkedin-in"></i></a>
            </div>
          </div>

          <div className="footer-section">
            <h3>Quick Links</h3>
            <ul className="footer-links">
              <li><a href="/">Home</a></li>
              <li><a href="/menu">Menu</a></li>
              <li><a href="/about">About Us</a></li>
              <li><a href="/contact">Contact</a></li>
            </ul>
          </div>

          <div className="footer-section">
            <h3>Services</h3>
            <ul className="footer-links">
              <li><a href="/daily-meals">Daily Meals</a></li>
              <li><a href="/special-diet">Special Diet</a></li>
              <li><a href="/meal-plans">Meal Plans</a></li>
              <li><a href="/quick-snacks">Quick Snacks</a></li>
            </ul>
          </div>

          <div className="footer-section">
            <h3>Contact Info</h3>
            <div className="footer-contact">
              <p><i className="fas fa-map-marker-alt"></i> Hostel Campus, University Road</p>
              <p><i className="fas fa-phone"></i> +1 234 567 8900</p>
              <p><i className="fas fa-envelope"></i> info@mealmate.com</p>
              <p><i className="fas fa-clock"></i> Mon - Sun: 7:00 AM - 10:00 PM</p>
            </div>
          </div>
        </div>

        <div className="footer-bottom">
          <p>&copy; {new Date().getFullYear()} MEALmate. All rights reserved.</p>
        </div>
      </footer>
    </div>
  );
}

export default Users;
